export default {
  PRIMARY: '#00BCD4',
  PRIMARY_DARK: '#0097A7',
  PRIMARY_LIGHT: '#B2EBF2',
  TEXT_PRIMARY: '#FFFFFF',
  TEXT_SECONDARY: '#757575',
  ICONS: '#FFFFFF',
  ACCENT: '#FF9800',
  DIVIDER: '#BDBDBD',
  BACKGROUND: '#FFFFFF',
  BUTTON_START: '#FAD961',
  BUTTON_END: '#FF9800',
  LIGHT: '#FFFFFF',
};
